import { Metadata } from "next";
import Navigation from "../components/navigation";

import "../styles/global.css"

export const metadata: Metadata = {
  title: { template: `%s | Next Movies`, default: "" },
  description: "Generated by Next.js",
};

// 모든 page파일은 layout 파일을 거쳐서 처리됨
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
